---
- name: install git
  become: yes
  apt: name=git state=latest

- name: stop any previously running instance
  # become: yes
  command: pkill java
  ignore_errors: yes # returns status code 1

- name: add github.ncsu.edu to known hosts
  become: yes
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.ncsu.edu') }}"
    regexp: "^github\\.ncsu\\.edu"

 # resetting because we modifies some files
- command: git reset --hard
  args:
    chdir: "/home/{{ansible_user}}/pdf-review-tool"
  ignore_errors: yes # returns status code 1    

- name: clone the pdf-review-tool repository
  git:
    repo: 'git@github.ncsu.edu:engr-csc-sdc/2018SpringTeam19.git'
    dest: "/home/{{ansible_user}}/pdf-review-tool"
    version: dev
    update: yes

- name: add environment variables
  become: yes
  lineinfile: 
    dest: /etc/environment 
    line: "{{item.name}}={{item.value}}"
  with_items: "{{env_vars}}"

- name: changing localhost to the actual ip address in src/main/webapp/js/login.js
  replace:
    path: "/home/{{ansible_user}}/pdf-review-tool/src/main/webapp/js/login.js"
    regexp: 'localhost'
    replace: '{{item}}'
    backup: yes
  with_items:
    - "{{inventory_hostname}}"

- name: ensure .aws directory exists
  file: 
    path: "/home/{{ansible_user}}/.aws"
    state: directory
    mode: 0755

- name: copying the credentials from template
  template:
    src: template/credentials.j2
    dest: "/home/{{ansible_user}}/.aws/credentials"

- name: mvn clean install
  command: mvn clean install
  args:
    chdir: "/home/{{ansible_user}}/pdf-review-tool"

# - name: start pdf-review-tool
#   command: mvn tomcat7:run
#   args:
#     chdir: "/home/{{ansible_user}}/pdf-review-tool"
